# Generated by Django 4.2.3 on 2023-08-26 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='stick',
            new_name='stock',
        ),
    ]
